CREATE TABLE t_raw1(
    brand NVARCHAR(MAX),
    model NVARCHAR(MAX),
    price_usd BIGINT NULL,
    ram_gb BIGINT NULL,
    storage_gb BIGINT NULL,
    camera_mp BIGINT NULL,
    battery_mah BIGINT NULL,
    display_size_inch FLOAT,
    charging_watt BIGINT NULL,
    _5g_support BIT,
    os NVARCHAR(MAX),
    processor NVARCHAR(MAX),
    rating FLOAT,
    release_month NVARCHAR(MAX),
    year BIGINT NULL)