table 'sqlserver38043.database.windows.net'
	lineageTag: 28acebbe-45e7-4c30-8388-0ec5e61427ca

	measure 'Average price phone' = AVERAGE('sqlserver38043.database.windows.net'[price_usd])
		lineageTag: 3541e734-141a-4311-b901-ac5b421d6860

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column brand
		dataType: string
		lineageTag: b9f0e254-a815-40e3-a4a7-665e2c8b6e6a
		summarizeBy: none
		sourceColumn: brand

		annotation SummarizationSetBy = Automatic

	column model
		dataType: string
		lineageTag: 58e497b4-4bb4-4bdf-a9a1-6c11b9aaadef
		summarizeBy: none
		sourceColumn: model

		annotation SummarizationSetBy = Automatic

	column model_var
		dataType: string
		lineageTag: a359362b-e590-42b8-a299-d6e6588cf152
		summarizeBy: none
		sourceColumn: model_var

		annotation SummarizationSetBy = Automatic

	column price_usd
		dataType: int64
		formatString: 0
		lineageTag: 3301eea4-3bbc-4a91-8528-bf6f20808ad4
		summarizeBy: sum
		sourceColumn: price_usd

		annotation SummarizationSetBy = Automatic

	column ram_gb
		dataType: int64
		formatString: 0
		lineageTag: 931368f8-4358-4e8e-8fe2-7aebf8a4bb7a
		summarizeBy: sum
		sourceColumn: ram_gb

		annotation SummarizationSetBy = Automatic

	column storage_gb
		dataType: int64
		formatString: 0
		lineageTag: 04e56c8b-41e0-4859-b71a-19b013025e27
		summarizeBy: sum
		sourceColumn: storage_gb

		annotation SummarizationSetBy = Automatic

	column camera_mp
		dataType: int64
		formatString: 0
		lineageTag: e452a40e-8983-486c-843f-c077421ba124
		summarizeBy: sum
		sourceColumn: camera_mp

		annotation SummarizationSetBy = Automatic

	column battery_mah
		dataType: int64
		formatString: 0
		lineageTag: 0d1c543d-c31f-4509-994c-c572abf0474d
		summarizeBy: sum
		sourceColumn: battery_mah

		annotation SummarizationSetBy = Automatic

	column display_size_inch
		dataType: double
		lineageTag: cd8ad665-5db3-49a8-819a-5f50d5a35fb1
		summarizeBy: sum
		sourceColumn: display_size_inch

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column charging_watt
		dataType: int64
		formatString: 0
		lineageTag: d3d4f269-8728-4d49-ab9a-f392296e1c8a
		summarizeBy: sum
		sourceColumn: charging_watt

		annotation SummarizationSetBy = Automatic

	column 5g_support
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: e06825d1-8d71-4d9a-ad3d-bc65d7643b8a
		summarizeBy: none
		sourceColumn: 5g_support

		annotation SummarizationSetBy = Automatic

	column os
		dataType: string
		lineageTag: b30d7a25-9ee6-42c5-8395-12c4316b822f
		summarizeBy: none
		sourceColumn: os

		annotation SummarizationSetBy = Automatic

	column processor
		dataType: string
		lineageTag: e99cd1cd-c885-4346-b749-bbc82209cf1d
		summarizeBy: none
		sourceColumn: processor

		annotation SummarizationSetBy = Automatic

	column rating
		dataType: double
		lineageTag: c51dd47a-34ab-4578-bd5d-4abeaca0e743
		summarizeBy: sum
		sourceColumn: rating

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column release_month
		dataType: int64
		formatString: 0
		lineageTag: 427a0f14-8bbf-4e60-83c3-418f595343d9
		summarizeBy: sum
		sourceColumn: release_month

		annotation SummarizationSetBy = Automatic

	column year
		dataType: int64
		formatString: 0
		lineageTag: b525db04-6f6a-44d1-b68d-0e9e6361cf47
		summarizeBy: sum
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	partition 'sqlserver38043.database.windows.net' = m
		mode: import
		source =
				let
				    source = Sql.Database("sqlserver38043.database.windows.net", "sqldb38043"),
				    dbo_clean_data = source{[Schema="dbo",Item="clean_data"]}[Data]
				in
				    dbo_clean_data

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

