name: Deploy Database

on:
  push:
    branches:
      - master

env:
  SQL_SERVER: ${{ secrets.SQL_SERVER }}
  SQL_DATABASE: ${{ secrets.SQL_DATABASE }}
  SQL_ADMIN: ${{ secrets.SQL_ADMIN_LOGIN }}
  SQL_PASSWORD: ${{ secrets.SQL_ADMIN_PASSWORD }}

jobs:
  deploy-db:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || true

      - name: Install sqlcmd (mssql-tools18)
        run: |
          curl https://packages.microsoft.com/config/ubuntu/22.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install -y mssql-tools18 unixodbc-dev
          echo 'export PATH="$PATH:/opt/mssql-tools18/bin"' >> ~/.bashrc
          source ~/.bashrc

      - name: Execute all SQL scripts in folder
        env:
          SQLCMDPASSWORD: ${{env.SQL_PASSWORD}}
        run: |
          find database -maxdepth 1 -type f -name "*.sql" | sort | while read file; do
            echo "Running $file"
            sqlcmd \ 
            -C -S ${{env.SQL_SERVER}} \
            -d ${{env.SQL_DATABASE}} \
            -U ${{env.SQL_ADMIN}} \
            -i "$file"
          done